# Generated by Django 5.2.2 on 2025-10-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='spots.spot'),
        ),
    ]
