# Generated by Django 5.2.9 on 2025-12-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_profile'),
        ('spots', '0006_title_usertitle'),
    ]

    operations = [
    ]
