# Generated by Django 5.2.8 on 2025-12-26 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_spots', to=settings.AUTH_USER_MODEL, verbose_name='お気に入り登録したユーザー'),
        ),
    ]
