# Generated by Django 5.2.8 on 2026-01-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_spot_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='作品名')),
                ('description', models.TextField(blank=True, verbose_name='作品説明')),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spots.work', verbose_name='作品'),
        ),
    ]
