# Generated by Django 5.2.8 on 2026-01-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_spot_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
