# Generated by Django 5.2.8 on 2026-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0010_work_spot_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='spot_type',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='title',
        ),
        migrations.AddField(
            model_name='work',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='作品画像URL'),
        ),
        migrations.AddField(
            model_name='work',
            name='representative_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表の聖地（場所）'),
        ),
    ]
