# Generated by Django 5.2.8 on 2026-01-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0011_remove_spot_spot_type_remove_spot_title_work_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='related_spot',
        ),
        migrations.AddField(
            model_name='title',
            name='related_work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='spots.work', verbose_name='対象作品'),
            preserve_default=False,
        ),
    ]
