# Generated by Django 5.2.8 on 2026-01-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0011_post_likes'),
        ('spots', '0012_remove_title_related_spot_title_related_work'),
    ]

    operations = [
    ]
