# Generated by Django 5.2.8 on 2026-01-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0014_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='related_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='spots.spot', verbose_name='対象聖地'),
        ),
    ]
